version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    build: ./
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - db
    ports:
      - '8080:80'

  db:
    image: mysql:latest
    ports:
    - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: Password123#@!
        MYSQL_DATABASE: cicd
        MYSQL_USER: bazengadaddy
        MYSQL_PASSWORD: Password123#@!

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_USER: bazengadaddy
      PMA_PASSWORD: Password123#@!
      UPLOAD_LIMIT: 3000000000
    ports:
      - "8000:80"