version: '3'
services:
  web:
    image: yiisoftware/yii2-php:7.2-apache
    container_name: ci_web
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
  db:
    image: mysql:latest
    container_name: ci_db
    environment:
        MYSQL_ROOT_PASSWORD: Password123#@!
        MYSQL_DATABASE: cicd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_USER: bazengadaddy
      PMA_PASSWORD: Password123#@!
      UPLOAD_LIMIT: 3000000000
    ports:
      - "8000:80"
    depends_on:
      - db
